'use client';
import {useState} from 'react';import {useRouter} from 'next/navigation';
const fmt=(n:number)=>new Intl.NumberFormat('nl-NL').format(n);
export default function AdminPanel({deposits,withdrawals,players}:{deposits:any[];withdrawals:any[];players:any[]}){
 const r=useRouter();const [msg,setMsg]=useState('');const [codes,setCodes]=useState<{registrationCode:string;verificationCode:string}|null>(null);
 async function post(url:string,body?:any){setMsg('Bezig…');const res=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await res.json().catch(()=>({}));setMsg(res.ok?'Actie uitgevoerd.':j.error||'Actie mislukt.');if(res.ok)r.refresh();return {ok:res.ok,j};}
 async function genCode(){const x=await post('/api/admin/codes',{action:'generate'});if(x.ok)setCodes(x.j)}
 return <div className="stack">
  {msg&&<div className={msg==='Actie uitgevoerd.'?'success':'card'}>{msg}</div>}
  <section className="card"><div className="row"><div><div className="eyebrow">Access control</div><h2>Toegangscodes</h2></div><button className="btn gold" onClick={genCode}>GENEREER CODEPAAR</button></div>{codes&&<div className="two" style={{marginTop:14}}><div className="card"><span className="muted">Registratiecode</span><div className="codeBox" style={{fontSize:'1.4rem'}}>{codes.registrationCode}</div></div><div className="card"><span className="muted">Verificatiecode</span><div className="codeBox" style={{fontSize:'1.4rem'}}>{codes.verificationCode}</div></div></div>}</section>
  <section className="card"><h2>Pending stortingen</h2><div className="tableWrap"><table className="table"><thead><tr><th>Speler</th><th>FiveM ID</th><th>Bedrag</th><th>Datum</th><th>Actie</th></tr></thead><tbody>{deposits.map(d=><tr key={d.id}><td>{d.users?.ingame_first_name} {d.users?.ingame_last_name}</td><td>{d.fivem_id}</td><td>${fmt(d.amount)}</td><td>{new Date(d.created_at).toLocaleString('nl-NL')}</td><td><button className="btn" onClick={()=>post(`/api/admin/deposits/${d.id}/approve`)}>Goedkeuren</button> <button className="btn danger" onClick={()=>post(`/api/admin/deposits/${d.id}/reject`)}>Afwijzen</button></td></tr>)}</tbody></table></div></section>
  <section className="card"><h2>Open uitbetalingen</h2><div className="tableWrap"><table className="table"><thead><tr><th>Speler</th><th>FiveM ID</th><th>Bedrag</th><th>Status</th><th>Actie</th></tr></thead><tbody>{withdrawals.map(w=><tr key={w.id}><td>{w.users?.ingame_first_name} {w.users?.ingame_last_name}</td><td>{w.fivem_id}</td><td>${fmt(w.amount)}</td><td><span className={'pill '+w.status}>{w.status}</span></td><td><button className="btn" onClick={()=>post(`/api/admin/withdrawals/${w.id}/approve`)}>Approve</button> <button className="btn gold" onClick={()=>post(`/api/admin/withdrawals/${w.id}/paid`)}>Paid</button> <button className="btn danger" onClick={()=>post(`/api/admin/withdrawals/${w.id}/reject`)}>Reject</button></td></tr>)}</tbody></table></div></section>
  <section className="card"><h2>Spelers & saldo</h2><div className="tableWrap"><table className="table"><thead><tr><th>Account</th><th>Ingame</th><th>FiveM</th><th>Saldo</th><th>Aanpassen</th></tr></thead><tbody>{players.map(p=><PlayerRow p={p} key={p.id} post={post}/>)}</tbody></table></div></section>
 </div>
}
function PlayerRow({p,post}:{p:any;post:(url:string,body?:any)=>Promise<any>}){const [amount,setAmount]=useState(0);const [reason,setReason]=useState('Handmatige RP-correctie');return <tr><td>{p.username}</td><td>{p.ingame_first_name} {p.ingame_last_name}</td><td>{p.fivem_id}</td><td>${fmt(p.wallets?.available_balance||0)}</td><td><input className="input" style={{width:115}} type="number" value={amount} onChange={e=>setAmount(Number(e.target.value))}/> <input className="input" style={{width:190}} value={reason} onChange={e=>setReason(e.target.value)}/> <button className="btn" onClick={()=>post('/api/admin/balance',{userId:p.id,amount,reason})}>Boek</button></td></tr>}
